version: "3"

services:
  # webapp:
  #   image: darchlabs/webapp:dev-beta-v4
  #   ports:
  #     - 3000:3000
  #   restart: on-failure
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres

  jobs:
    image: darchlabs/jobs:1.1.7
    ports:
      - 3030:3030
    restart: on-failure
    env_file:
      - .env.jobs
    volumes:
      - ./data/jobs:/home/jobs/data:rw
    depends_on:
      - postgres

  # synchronizers:
  #   image: darchlabs/synchronizer-v2:1.9.0
  #   ports:
  #     - 5555:5555
  #   restart: always
  #   env_file:
  #     - .env.synchronizers
  #   volumes:
  #     - ./data/sync:/home/sync/data:rw

  # postgres:
  #   image: postgres:latest
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data
