version: "3.9"

services:
  webapp:
    image: darchlabs/webapp
    env_file:
      - ./.env
    ports:
      - "3000:3000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/redis
